-- PREGUNTA 1

select E.first_name,
       E.hire_date,
       E.salary,
       D.Department_Name,
       J.JOB_TITLE
from employees E,
     departments D,
     jobs J
where E.SALARY >= 4500 and
      E.SALARY < 15000 and
      E.Department_Id = D.DEPARTMENT_ID and
      E.Job_Id = J.JOB_ID     

-- PREGUNTA 2

SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       C.COUNTRY_NAME

FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L,
     COUNTRIES C
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
      E.JOB_ID = 'FI_ACCOUNT' AND
      D.LOCATION_ID = L.LOCATION_ID AND
      L.COUNTRY_ID = C.COUNTRY_ID
      
      
-- PREGUNTA 3
      
SELECT E.*
FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
      D.LOCATION_ID = L.LOCATION_ID AND
      (L.CITY = 'Mexico City' OR L.COUNTRY_ID = 'US')
      
-- PREGUNTA 4

SELECT E.*
FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
      E.DEPARTMENT_ID = 80 AND
      D.LOCATION_ID = L.LOCATION_ID AND
      L.COUNTRY_ID = 'UK'

-- PREGUNTA 5


SELECT E.FIRST_NAME, E.LAST_NAME
FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L,
     COUNTRIES C
WHERE E.SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES) AND
      E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
      D.LOCATION_ID = L.LOCATION_ID AND
      L.COUNTRY_ID = C.COUNTRY_ID AND
      C.REGION_ID = 2


-- PREGUNTA 6

SELECT C.COUNTRY_NAME,
       R.REGION_NAME,
       (SELECT COUNT (*)
        FROM EMPLOYEES E,
             DEPARTMENTS D,
             LOCATIONS L,
             COUNTRIES C
        WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
              D.LOCATION_ID = L.LOCATION_ID AND
              L.COUNTRY_ID = C.COUNTRY_ID
       ) AS CANT_EMPLOYEES
FROM REGIONS R,
     COUNTRIES C
WHERE C.REGION_ID = R.REGION_ID /*falta uu*/
      
